version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend/react-btcweb
    container_name: react-btcweb
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/react-btcweb/src:/app/src
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=(PUBLIC IP):8080
  backend:
    image: springboot-btcweb:LATEST
    build:
      context: ./backend/springboot-btcweb
    container_name: springboot-btcweb
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/btc_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      
  db:
    image: postgres:14.2-alpine
    restart: always
    volumes:
      - ./db/var/lib/postgresql/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: btc_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  