version: '3'
services:
  frontend:
    build: ./frontend/react-btcweb
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/react-btcweb/src:/app/src
    env_file:
      - ./frontend/react-btcweb/.env

