version: '3'
services:
  frontend:
    build: ./frontend/react-btcweb
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/react-btcweb/src:/app/src
    env_file:
      - ./frontend/react-btcweb/.env
  db:
    image: postgres:14.2-alpine
    restart: always
    volumes:
      - ./db/var/lib/postgresql/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: btc_db
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
