CREATE TABLE IF NOT EXISTS ACCOUNT (
	ACC_ID SERIAL NOT NULL,
	ACC_NAME VARCHAR(255) NOT NULL,
	ACC_CPF VARCHAR(15) NOT NULL,
	ACC_EMAIL VARCHAR(150) NOT NULL,
	ACC_PASSWORD VARCHAR(100) NOT NULL,
	CONSTRAINT PK_ACC_ID PRIMARY KEY(ACC_ID)
);
CREATE TABLE IF NOT EXISTS JOB (
	JOB_ID SERIAL NOT NULL,
	JOB_NAME VARCHAR(255) NOT NULL,
	CONSTRAINT PK_JOB_ID PRIMARY KEY(JOB_ID)
);
CREATE TABLE IF NOT EXISTS ACCOUNT_JOB (
	ACC_JOB_ID SERIAL NOT NULL,
	ACC_ID SERIAL NOT NULL,
	JOB_ID SERIAL NOT NULL,
	CONSTRAINT PK_ACC_JOB_ID PRIMARY KEY(ACC_JOB_ID)
);


CREATE TABLE IF NOT EXISTS REQUEST (
	REQ_ID SERIAL NOT NULL,
	ACC_ID INTEGER NOT NULL,
	REQ_TIME TIMESTAMP,
	REQ_TOTAL DECIMAL(10,2),
	CONSTRAINT PK_REQ_ID PRIMARY KEY(REQ_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT(
	PROD_ID SERIAL NOT NULL,
	PROD_NAME VARCHAR(255) NOT NULL,
	PROD_DESCRIPTION TEXT,
	PROD_PRICE NUMERIC(10,2) NOT NULL,
	PROD_ACTIVE BOOLEAN NOT NULL,
	CONSTRAINT PK_PROD_ID PRIMARY KEY(PROD_ID)
);

CREATE TABLE IF NOT EXISTS REQUEST_PRODUCT(
	REQ_PROD_ID SERIAL NOT NULL,
	REQ_PROD_AMOUNT INTEGER NOT NULL,
	REQ_ID INTEGER NOT NULL,
	PROD_ID INTEGER NOT NULL,
	CONSTRAINT PK_REQ_PROD_ID  PRIMARY KEY(REQ_PROD_ID )
);

CREATE TABLE IF NOT EXISTS UNIT (
	UN_ID SERIAL NOT NULL,
	UN_NAME VARCHAR(255) NOT NULL,
	UN_SYMBOL VARCHAR(4) NOT NULL,
	CONSTRAINT PK_UN_ID PRIMARY KEY (UN_ID)
);

CREATE TABLE IF NOT EXISTS INGREDIENT (
	ING_ID SERIAL NOT NULL,
	ING_NAME VARCHAR (255) NOT NULL,
	ING_STOCK_QUANTI INTEGER NOT NULL,
	ING_EXPIRATION_DATE TIMESTAMP,
	UN_ID INTEGER NOT NULL,
	CONSTRAINT PK_ING_ID PRIMARY KEY (ING_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_INGREDIENT (
	PROD_ING_ID SERIAL NOT NULL,
	ING_ID INTEGER NOT NULL,
	PROD_ID INTEGER NOT NULL,
	PROD_ING_AMOUNT DECIMAL (10,2),
	CONSTRAINT PK_PROD_ING_ID PRIMARY KEY (PROD_ING_ID)
);



ALTER TABLE ACCOUNT_JOB  ADD CONSTRAINT FK_ACC_ID FOREIGN KEY(ACC_ID) REFERENCES ACCOUNT (ACC_ID);
ALTER TABLE ACCOUNT_JOB  ADD CONSTRAINT FK_JOB_ID FOREIGN KEY(JOB_ID) REFERENCES JOB (JOB_ID);

ALTER TABLE REQUEST_PRODUCT ADD CONSTRAINT FK_REQ_ID FOREIGN KEY(REQ_ID) REFERENCES REQUEST (REQ_ID);
ALTER TABLE REQUEST_PRODUCT ADD CONSTRAINT FK_PROD_ID FOREIGN KEY(PROD_ID) REFERENCES PRODUCT (PROD_ID);

ALTER TABLE INGREDIENT  ADD CONSTRAINT FK_UN_ID FOREIGN KEY(UN_ID) REFERENCES UNIT (UN_ID);

ALTER TABLE PRODUCT_INGREDIENT ADD CONSTRAINT FK_ING_ID FOREIGN KEY(ING_ID) REFERENCES INGREDIENT (ING_ID);
ALTER TABLE PRODUCT_INGREDIENT ADD CONSTRAINT FK_PROD_ID FOREIGN KEY(PROD_ID) REFERENCES PRODUCT (PROD_ID);




